<a href="https://colab.research.google.com/github/ranggaart/Data_Mining-P.7/blob/main/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
import matplotlib.pyplot as plt





In [31]:
# Load dataset iris dari library scikit learn
iris = datasets.load_iris()
features = iris['data']
target = iris['target']

print(features)
len(features)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

150

In [32]:
# Membuat Objek Model Decision Tree
decisiontree = DecisionTreeClassifier(random_state=0, max_depth=None,
                                      min_samples_split=2, min_samples_leaf=1,
                                      min_weight_fraction_leaf=0,
                                      max_leaf_nodes=None,
                                      min_impurity_decrease=0)

In [33]:
# Training Model Decision Tree
model = decisiontree.fit(features, target)

In [34]:
# Mengambil sampel observasi dan membuat prediksi
observation = [[5, 4, 3, 2]]
model.predict(observation)
model.predict_proba(observation)

array([[0., 1., 0.]])

In [35]:
# Grafik
import pydotplus
from sklearn import tree
from IPython.display import Image

dot_data = tree.export_graphviz(decisiontree, out_file=None,
                                feature_names=iris['feature_names'],
                                class_names=iris['target_names'])
graph = pydotplus.graph_from_dot_data(dot_data)
Image(graph.create_png())
graph.write_png('iris.png')


True

**DecisionTree dengan Dataset **

In [2]:
import pandas as pd
import numpy as np
from sklearn import tree

In [5]:
# Dataset
irisDataset = pd.read_csv('data_iris.csv', delimiter=',', header=0)
len(irisDataset)


152

In [7]:
irisDataset.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

           Species  
0  iris-versicolor  
1  iris-versicolor  
2  iris-versicolor  
3  iris-versicolor  
4  iris-versicolor

In [9]:
# Mengubah kelas (kolom "species") dari string ke unique-integer
irisDataset["species"] = pd.factorize(irisDataset.Species)[0]

In [10]:
print(irisDataset)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
147                6.7               3.0                5.2               2.3   
148                6.3               2.5                5.0               1.9   
149                6.5               3.0                5.2               2.0   
150                6.2               3.4                5.4               2.3   
151                5.9               3.0                5.1               1.8   

             Species  speci

In [16]:
# Membagi Dataset 100 baris data
dataTraining = np.concatenate((irisDataset.iloc[0:50, :], irisDataset.iloc[50:100, :]), axis=0)
dataTesting = np.concatenate((irisDataset.iloc[50:60, :], irisDataset.iloc[100:110, :]),
                            axis=0)

In [15]:
print(dataTraining)
len(dataTraining)

[[5.1 3.5 1.4 0.2 'iris-versicolor' 0]
 [4.9 3.0 1.4 0.2 'iris-versicolor' 0]
 [4.7 3.2 1.3 0.2 'iris-versicolor' 0]
 [4.6 3.1 1.5 0.2 'iris-versicolor' 0]
 [5.0 3.6 1.4 0.2 'iris-versicolor' 0]
 [5.4 3.9 1.7 0.4 'iris-versicolor' 0]
 [4.6 3.4 1.4 0.3 'iris-versicolor' 0]
 [5.0 3.4 1.5 0.2 'iris-versicolor' 0]
 [4.4 2.9 1.4 0.2 'iris-versicolor' 0]
 [4.9 3.1 1.5 0.1 'iris-versicolor' 0]
 [5.4 3.7 1.5 0.2 'iris-versicolor' 0]
 [4.8 3.4 1.6 0.2 'iris-versicolor' 0]
 [4.8 3.0 1.4 0.1 'iris-versicolor' 0]
 [4.3 3.0 1.1 0.1 'iris-versicolor' 0]
 [5.8 4.0 1.2 0.2 'iris-versicolor' 0]
 [5.7 4.4 1.5 0.4 'iris-versicolor' 0]
 [5.4 3.9 1.3 0.4 'iris-versicolor' 0]
 [5.1 3.5 1.4 0.3 'iris-versicolor' 0]
 [5.7 3.8 1.7 0.3 'iris-versicolor' 0]
 [5.1 3.8 1.5 0.3 'iris-versicolor' 0]
 [5.4 3.4 1.7 0.2 'iris-versicolor' 0]
 [5.1 3.7 1.5 0.4 'iris-versicolor' 0]
 [4.6 3.6 1.0 0.2 'iris-versicolor' 0]
 [5.1 3.3 1.7 0.5 'iris-versicolor' 0]
 [4.8 3.4 1.9 0.2 'iris-versicolor' 0]
 [5.0 3.0 1.6 0.2 'iris-v

100

In [17]:
print(dataTesting)
len(dataTesting)

[[5.3 3.7 1.5 0.2 'iris-versicolor' 0]
 [5.0 3.3 1.4 0.2 'iris-versicolor' 0]
 [7.0 3.2 4.7 1.4 'iris-virginica' 1]
 [6.4 3.2 4.5 1.5 'iris-virginica' 1]
 [6.9 3.1 4.9 1.5 'iris-virginica' 1]
 [5.5 2.3 4.0 1.3 'iris-virginica' 1]
 [6.5 2.8 4.6 1.5 'iris-virginica' 1]
 [5.7 2.8 4.5 1.3 'iris-virginica' 1]
 [6.3 3.3 4.7 1.6 'iris-virginica' 1]
 [4.9 2.4 3.3 1.0 'iris-virginica' 1]
 [5.1 2.5 3.0 1.1 'iris-virginica' 1]
 [5.7 2.8 4.1 1.3 'iris-virginica' 1]
 [6.3 3.3 6.0 2.5 'iris-sentosa' 2]
 [5.8 2.7 5.1 1.9 'iris-sentosa' 2]
 [7.1 3.0 5.9 2.1 'iris-sentosa' 2]
 [6.3 2.9 5.6 1.8 'iris-sentosa' 2]
 [6.5 3.0 5.8 2.2 'iris-sentosa' 2]
 [7.6 3.0 6.6 2.1 'iris-sentosa' 2]
 [4.9 2.5 4.5 1.7 'iris-sentosa' 2]
 [7.3 2.9 6.3 1.8 'iris-sentosa' 2]]


20

In [20]:
# Memecah Dataset ke Input dan Label
inputTraining = dataTraining[:, 0:4]
inputTesting = dataTesting[:, 0:4]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]

In [18]:
# Mendefinisikan Decision Tree Classifier
model = tree.DecisionTreeClassifier()

In [21]:
# Mentraining Model
model = model.fit(inputTraining, labelTraining)

In [22]:
# Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  ['iris-versicolor' 'iris-versicolor' 'iris-virginica' 'iris-virginica'
 'iris-virginica' 'iris-virginica' 'iris-virginica' 'iris-virginica'
 'iris-virginica' 'iris-virginica' 'iris-virginica' 'iris-virginica'
 'iris-sentosa' 'iris-sentosa' 'iris-sentosa' 'iris-sentosa'
 'iris-sentosa' 'iris-sentosa' 'iris-sentosa' 'iris-sentosa']
Hasil Prediksi :  ['iris-versicolor' 'iris-versicolor' 'iris-virginica' 'iris-virginica'
 'iris-virginica' 'iris-virginica' 'iris-virginica' 'iris-virginica'
 'iris-virginica' 'iris-virginica' 'iris-virginica' 'iris-virginica'
 'iris-virginica' 'iris-virginica' 'iris-virginica' 'iris-virginica'
 'iris-virginica' 'iris-virginica' 'iris-virginica' 'iris-virginica']


In [24]:
# Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi : ", prediksiBenar/(prediksiBenar + prediksiSalah) * 100, "%")

Prediksi Benar : 12 data
Prediksi Salah : 8 data
Akurasi :  60.0 %
